apiVersion: v1
kind: ReplicationController
metadata: 
  name: myrc
spec: 
  replicas: 2
  selector: 
    app: myapp1
  template:
    metadata: 
     name: pod1
     labels: 
      app: myapp1
    spec: 
      containers:
        - name: c1
          image: nginx
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: myservice
spec: 
  type: NodePort
  selector:
    app: myapp1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  

