apiVersion: batch/v1
kind: Job
metadata: 
  name: myjob
spec:
  backoffLimit: 4
  completions: 4
  parallelism: 2
  template:
   spec: 
     containers: 
       - name: mycontainer
         image: alpine:latest
         command: ["bin/sh", "-c"]
         args: ["echo hello world"]
     restartPolicy: Never
