apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myrs
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app1: myapp1
  template:
    metadata: 
     name: mypod
     labels: 
      app1: myapp1
    spec: 
      containers:
        - name: m1
          image: ubuntu/apache2
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: myservice2
spec: 
  type: NodePort
  selector:
    app1: myapp1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
  

