apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemonset
spec:
  selector:
    matchLabels: 
      app: myapp
  template:
    metadata:
      name: mypod
      labels: 
        app: myapp
    spec:
      containers:
        - name: c1
          image: ubuntu/apache2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
