apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: frontend
spec:
  replicas: 3
  selector: 
    matchLabels:
      type: frontend
  template: 
   metadata:
    labels: 
     type: frontend
   spec:
    containers: 
     - name: mywebserver
       image: nginx:1.7.9
       ports:
        - containerPort: 80
